<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Users PDF</title>
</head>

<body>
    <div style="margin-bottom:25px;"><strong>Report generated by: {{$param}}</strong></div>
    <table style="border-collapse: collapse;">
        <thead>
            <tr>
                <th style="border-bottom:2pt solid black;">
                    <strong>ID</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Name</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Email</strong>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
            <tr>
                <td style="border-bottom:1pt solid black;">
                    {{$user->id}}
                </td>
                <td style="border-bottom:1pt solid black;">
                    {{$user->name}}
                </td>
                <td style="border-bottom:1pt solid black;">
                    {{$user->email}}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>